language: python
# command to install dependencies
install:
    - pip install tox distribute setuptools -U
    - python bootstrap.py
    - bin/buildout
# # command to run tests
script: tox
after_success:
  - bin/coverage run bin/test
  - bin/coveralls
notifications:
    email:
        - bubenkoff@gmail.com
