language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install: 
    - python bootstrap.py
    - bin/buildout
# # command to run tests
script: bin/test
after_success:
  - bin/coverage run bin/test
  - bin/coveralls
notifications:
    email:
        - bubenkoff@gmail.com
